# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-11"

  config.vm.communicator = "winrm"
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  config.vm.box_check_update = false


  # Configuração para VMware Workstation
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4096"  # Ajuste a memória conforme necessário
    v.vmx["numvcpus"] = "4"    # Ajuste o número de CPUs conforme necessário
    v.vmx["ethernet0.pcislotnumber"] = "192"
    v.gui = true               # Habilita a interface gráfica do VMware, se necessário
  end



  # Provisionamento com PowerShell
  config.vm.provision "shell", inline: <<-SHELL
    # Exibe informações de licença
    slmgr -dlv

    # Extende o período de avaliação
    slmgr -rearm

    # Reinicia o computador
    Restart-Computer -Force

    # Aguarda a reinicialização
    Start-Sleep -Seconds 60

    # Verifica as configurações após a reinicialização
    slmgr -dli
  SHELL
end
